{{- range $name, $config := .Values.persistentVolumeClaims }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "generic.fullname" (dict "root" $ "name" $name) }}
  labels:
    {{- include "generic.labels" (dict "root" $ "name" $name) | nindent 4 }}
  {{- with $config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ $config.accessMode | default "ReadWriteOnce" | quote }}
  resources:
    requests:
      storage: {{ $config.size | default "8Gi" | quote }}
  {{- /* an explicit empty string ("") disables dynamic provisioning, so distinguish unset from empty */}}
  {{- if not (kindIs "invalid" $config.storageClass) }}
  storageClassName: {{ $config.storageClass | quote }}
  {{- end }}
{{- end }}
