{{- range $name, $config := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic.fullname" (dict "root" $ "name" $name) }}
  labels:
    {{- include "generic.labels" (dict "root" $ "name" $name) | nindent 4 }}
type: {{ $config.type | default "Opaque" }}
{{- with $config.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with $config.stringData }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
