{{- range $name, $config := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "generic.labels" (dict "name" $name) | nindent 4 }}
type: {{ $config.type | default "Opaque" }}
stringData:
  {{- toYaml $config.stringData | nindent 2 }}
{{- end }}
