{{- range $name, $config := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Chart.Name }}-{{ $name }}
  labels:
    {{- include "generic.labels" (dict "chartName" $.Chart.Name "name" $name) | nindent 4 }}
spec:
  type: {{ $config.type | default "ClusterIP" }}
  {{- with $config.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- toYaml ($config.selector | default (dict "app.kubernetes.io/name" (printf "%s-%s" $.Chart.Name $name))) | nindent 4 }}
{{- end }}
