{{- range $name, $config := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic.fullname" (dict "root" $ "name" $name) }}
  labels:
    {{- include "generic.labels" (dict "root" $ "name" $name) | nindent 4 }}
  {{- with $config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $config.type | default "ClusterIP" }}
  {{- with $config.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with $config.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- if $config.selector }}
    {{- toYaml $config.selector | nindent 4 }}
    {{- else }}
    {{- include "generic.selectorLabels" (dict "root" $ "name" $name) | nindent 4 }}
    {{- end }}
{{- end }}
